<?php


/**
 * This class adds structure of 'account' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 07/11/09 22:07:29
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.auth.map
 */
class AccountMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.auth.map.AccountMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AccountPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AccountPeer::TABLE_NAME);
		$tMap->setPhpName('Account');
		$tMap->setClassname('Account');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('CID', 'Cid', 'VARCHAR', true, 64);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', true, 64);

		$tMap->addColumn('PASSWORD', 'Password', 'VARCHAR', true, 64);

		$tMap->addColumn('FIRST_NAME', 'FirstName', 'VARCHAR', false, 64);

		$tMap->addColumn('LAST_NAME', 'LastName', 'VARCHAR', false, 64);

		$tMap->addColumn('COO_REMEMBER', 'CooRemember', 'VARCHAR', false, 32);

		$tMap->addColumn('IS_ACTIVE', 'IsActive', 'TINYINT', true, 1);

		$tMap->addColumn('IS_DELETED', 'IsDeleted', 'TINYINT', true, 1);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('MODIFIED_AT', 'ModifiedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('DELETED_AT', 'DeletedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // AccountMapBuilder
