












# default rules (my)
homepage:
  url:   /
  param: { module: core, action: index }

core_index:
  url:   /:module
  param: { action: index }

core:
  url:   /:module/:action/*


### default rules
##homepage:
##  url:   /
##  param: { module: default, action: index }
##
##default_index:
##  url:   /:module
##  param: { action: index }
##
##default:
##  url:   /:module/:action/*
##  