


### Page Rules
page_home:
  url:   /index
  param: { module: page, action: index }

page_what-we-do:
  url:   /what-we-do
  param: { module: page, action: whatWeDo }

page_how-we-work:
  url:   /how-we-work
  param: { module: page, action: howWeWork }

page_about-us:
  url:   /about-us
  param: { module: page, action: aboutUs }

page_our-works:
  url:   /our-works
  param: { module: page, action: ourWorks }

page_contact:
  url:   /contact
  param: { module: page, action: contact }




### default rules (my)
homepage:
  url:   /
  param: { module: page, action: index }

core_index:
  url:   /:module
  param: { action: index }

core:
  url:   /:module/:action/*


### default rules
##homepage:
##  url:   /
##  param: { module: default, action: index }
##
##default_index:
##  url:   /:module
##  param: { action: index }
##
##default:
##  url:   /:module/:action/*
##  